name: Translations Validation on PR

on:
  pull_request:
    branches:
      - "*"
      - "*/*"

jobs:
  validate_pr_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          pip3 install jsonschema

      - name: Find and list modified auth.json files
        id: getfiles
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'auth.json' || true)
          if [ -z "$files" ]; then
            echo "No changed auth.json files to validate."
            echo "::set-output name=files_to_validate::"
          else
            echo "Changed files: $files"
            echo "::set-output name=files_to_validate::$files"
          fi

      - name: Validate JSON files
        if: steps.getfiles.outputs.files_to_validate
        run: |
          python validate_json.py auth-schema.json ${{ steps.getfiles.outputs.files_to_validate }}
