name: Validate JSON files
on:
  pull_request:
    branches:
      - "*"
      - "*/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/auth.json

      - name: List all changed files
        if: steps.changed-files.outputs.all_changed_files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Validate JSON files
        if: steps.changed-files.outputs.all_changed_files
        run: |
          python3 validate-json.py auth-schema.json ${{ steps.changed-files.outputs.all_changed_files }}
