name: Translations Validation

on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # necessary to get full history for comparison

      - name: Setup Git to access main branch from upstream
        run: |
          git remote add upstream https://github.com/kinde-oss/kinde-translations.git
          git fetch upstream main:upstream-main

      - name: Find changes compared to main branch
        run: |
          git diff --name-only upstream-main...${{ github.sha }} > changes.txt
          if [ -s changes.txt ]; then
            echo "CHANGED_FILES=$(<changes.txt)" >> $GITHUB_ENV
            echo "Changed files:"
            cat changes.txt
          else
            echo "No changes detected."
        shell: bash
