name: Check Changed Files

on:
  pull_request:
    branches:
      - "*"
      - "*/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          repository: "kinde-oss/kinde-translation"
          ref: "main"
          path: "base"

      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          repository: "${{ github.event.pull_request.head.repo.full_name }}"
          ref: "${{ github.event.pull_request.head.ref }}"
          path: "pr"

      - name: Get changed files
        run: |
          cd base
          git fetch origin
          git diff --name-only origin/main..origin/${{ github.event.pull_request.head.ref }} > ../changed_files.txt
          cd ..
          cat changed_files.txt
